<?php 

if($this->_action=='admin' || $this->_readonly==1)
{
    if($this->_Value)
    {
        $fileName=Core::getUploadPath();
        if($this->_filePath)
        {
            $fileName.=$this->_filePath."/";
        }
        $fileName.=$this->_Value;
        echo "<a href='".$fileName."' target='_blank' >view</a>";
    }
    else
    {
        echo $this->_Value;
    }
}
else
{
    $fileName="";
    if($this->_Value)
    {
        $fileName=Core::getUploadPath();
        if($this->_filePath)
        {
            $fileName.=$this->_filePath."/";
        }
        $fileName.=$this->_Value;
    }
    ?>
    <div class="control" id="value_<?php echo $this->_idName;?>">
        <a href="javascript: void(0);" target="_center" onclick="popup('<?php echo $fileName;?>');" >
            <img src="<?php echo $fileName;?>" alt='File' style=" max-width: 250px; max-width: 200px;">
        </a>
        <div class="checker" id="uniform-check_<?php echo $this->_idName;?>">
            <span><input type="checkbox" name="check_<?php echo $this->_idName;?>" id="check_<?php echo $this->_idName;?>" value="1" style="opacity: 0;"></span>
        </div> Remove File<input type="file" name="<?php echo $this->_idName;?>" id="<?php echo $this->_idName;?>" value="<?php echo $this->_Value; ?>">
        
    </div>
    <script type="text/javascript">
        function popup(url)
        {
            window.open(url);
        }
    </script>
<?php
}
?>